### ISSUE TITLE
Better support style attribute somehow

### ISSUE THREAD

**Issue by kevinresol** [MVCoconut/coconut.haxeui#2]
Currently `<Button style=${{width: 100}}/>` doesn't work because style is a class instance of `Style`, not an anon object.

**Comment by kevinresol** [comment]
Closed by https://github.com/haxeui/haxeui-core/pull/358

**Comment by back2dos** [comment]
Oh, nice. Otherwise, it could be dealt with via [`@:fromHxx`](https://github.com/haxetink/tink_domspec/blob/e7d729b5640d7fff842835a4972f7f2a4b59ee84/src/tink/domspec/Style.hx#L3) ;)
